%% Max Kramer
% I affirm that I have adhered to the honor code on this assignment.

%%
% _Hello again, scientist! I'll do all my writing in italics, and problems for you will be in *bold.*
% Comment your code, and_ explain your ideas in plaintext. _As a general rule, I expect
% you to do at least as much writing as I do. Code should be part of your solution, but
% I expect variables to be clear and explanation to involve complete sentences.
% Cite your sources; if you work with someone in the class on a problem,
% that's an extremely important source. Don't work alone._

%% Problem 12.1.
% 

v1 = [1;2;3;4;5]; v2 = [0;1;0;-1;1];

%%
% _*Find a 3x5 matrix A for which Null(A) = Span{v1,v2}. 
% Prove that your answer works.* Students last year found this problem
% to be much more difficult than it appears, so here's a hint: use Theorem 3 
% in Lay 6.1 to find a basis for the orthogonal complement of Span{v1,v2}._

V = [v1 v2];
Sys = horzcat(V',[0;0]);
PVF = [-3 0 1 0 0;-6 1 0 1 0;-3 -1 0 0 1]'

t = PVF'
t * v1
t * v2

%%
% The matrix V is created by concatenating v1 and v2. Theorem 3 in Lay 6.1 says that the column space of A is the orthogonal compliment of the null space of A'. To find the 3 x 5 matrix of interest, we crete an augmented system from V' and calculate the general solution. Parametric vector form (done by hand) found three vectors that make up the matrix PVF. Since we want the Null space of A and not A', we transpose the vectors and arrive at a 3 x 5 matrix PVF'. Multiplying this matrix by v1 and v2 yields the zero vector in both cases, so PVF' is a 3 x 5 matrix for which Null(PVF') = span{v1,v2}.

%%
% _*Find a square matrix B for which Null(B) = Span{v1,v2}. Prove that your
% answer works.* You can use the previous part, or you can be clever in
% other ways._

step2 = horzcat(PVF,[-11;0;1;-1;1])
step3 = horzcat(step2,[-7;1;-1;1;0])

final = step3'

dot(final(4,:),v1)
dot(final(4,:),v2)
dot(final(5,:),v1)
dot(final(5,:),v2)

%%
% The matrix final is generated by promoting the 3 x 5 matrix found in the
% previous step with two rows that are elements of the orthogonal
% complement of Span{v1,v2}. As the orthogonal complement of the row space
% of Span{v1,v2} is the null space of Span{v1,v2}, the null space should
% be unaffected by the addition of vectors already contained within the
% span.